package constants

object ActionTypes{
    val ADD_TO_CART = "ADD_TO_CART"
    val CHECKOUT_REQUEST = "CHECKOUT_REQUEST"
    val CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
    val CHECKOUT_FAILURE = "CHECKOUT_FAILURE"
    val RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS"
}